INSERT INTO taxpays VALUES ("DE", "Allemagne", 0.17);
INSERT INTO taxpays VALUES ("ES", "Espagne", 0.21);
INSERT INTO taxpays VALUES ("FR", "France", 0.2);
INSERT INTO taxpays VALUES ("GB", "Royaume Unis", 0.19);
INSERT INTO taxpays VALUES ("US", "Etats Unis", 0.18);
INSERT INTO taxpays VALUES ("IE", "Irlande", 0.22);
INSERT INTO taxpays VALUES ("FI", "Finlande", 0.24);
INSERT INTO taxpays VALUES ("MT", "Malte", 0.1);
INSERT INTO taxpays VALUES ("DK", "Danemark", 0.25);
INSERT INTO taxpays VALUES ("NL", "Pays Bas", 0.21);
INSERT INTO taxpays VALUES ("BE", "Belgique", 0.21);
INSERT INTO taxpays VALUES ("PL", "Pologne", 0.22);
INSERT INTO taxpays VALUES ("IT", "Italie", 0.22);
INSERT INTO taxpays VALUES ("JP", "Japon", 0.13);
INSERT INTO taxpays VALUES ("CN", "Chine", 0.17);
INSERT INTO taxpays VALUES ("AU", "Australie", 0.17);
INSERT INTO taxpays VALUES ("CA", "Canada", 0.16);
INSERT INTO taxpays VALUES ("IN", "Inde", 0.15);
INSERT INTO taxpays VALUES ("PT", "Portugal", 0.13);